name: dart_westminster_standards
description: A Dart package providing the Westminster Confession of Faith, Shorter Catechism, and Larger Catechism with proof texts.
version: 0.0.3

environment:
  sdk: ^3.7.2

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
